### ISSUE TITLE
syto16.tiff file missing

### ISSUE THREAD

**Issue by LeeKamentsky** [chunglabmit/phathom#3]
Hey @jmswaney - build is breaking in Travis because https://github.com/chunglabmit/phathom/blob/master/tests/test_celltype.py#L19 has a local path. Several ways to go about fixing this:
* Make syto16.tif, sox2.tif, tbr1.tif files small (< 1Mb) and include them in the test directory and use os.path.dirname(__file__) + "/syto16.tif" to reference them.
* Leave them somewhat large, host them on google drive or similar and write code to load them.
* Make toy examples using numpy arrays.

If you want me to take care of this, I can do the second one if you upload the files and give me links or I can do the first one if you check the files into the repo.

**Comment by jmswaney** [comment]
I would say the first option if I had to pick one, but I don't think the tif-based tests actually assert anything. This was just my bad habit of prototyping some ideas while also writing tests on mock numpy arrays.

**Comment by jmswaney** [comment]
My intention was to only load the images in if `test_images` was `True`, which would mean I was running locally and wanted to see it on real images. I just forgot to put the tiff reading lines in an if-block
